server:
  port: 8080
  displayName: netty-learning

jetty:
  threadPool:
      maxThreads: 200
      minThreads: 10
      idleTimeout: 30000

mybatis:
    configLocation: classpath:/mybatis-config.xml